### ISSUE TITLE
Weapon id page too long to render

### ISSUE THREAD

**Issue by oldflag2333333** [mhvuze/MonsterHunterRiseModding#21]
![image](https://user-images.githubusercontent.com/53090940/185631665-dbc31fa9-0471-45e4-b903-4fc27464f7e8.png)

**Comment by Built4anything** [comment]
I'm having the same issue. Has someone found a resolution for this? Sort of need this page to make adjustments to mods.

**Comment by Hroken1** [comment]
Yup! Same issue here.

**Comment by robinwei101** [comment]
i guess it needs to be broken down into weapon types

**Comment by oldflag2333333** [comment]
fixed

**Comment by Synthlight** [comment]
> fixed

No, it absolutely wasn't. Some with more processing power run into the issue less and it works sometimes. But the core issue still remains.

**Comment by dtlnor** [comment]
As the page now split into 3 pages. I think it should be fixed.
